version: '3'
services:
  playground:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
    volumes:
      - ./quantum-power-system-state-estimation/experiments

  dev:
    build:
      context: .
      dockerfile: dev.dockerfile