version: '3'
services:
  playground:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
    volumes:
      - ./experiments
    command: 

  dev:
    build:
      context: .
      dockerfile: dev.dockerfile